hopper_name: "&bCrop &7Hopper"
hopper_lore: "&7Magical Cactus Hopper!"

messages:
    hopper_already_in_chunk: "&b&lAscendPvP &7> There is already a &bCrop &7Hopper in this chunk!"
    hopper_break_success: "&b&lAscendPvP &7> You successfully broke a &bCrop &7Hopper!"
    hopper_place_success: "&b&lAscendPvP &7> You successfully placed a &bCrop &7Hopper! Right-click a chest to do that, or right-click this hopper for default behavior!"
    hopper_place_fail: "You can only place hoppers iun your own plot/plots youre added tol"
    hopper_redirect_success: "Successfully set this CropHopper's behavior! re set to change"
    hopper_redirect_dont: "Successfully set this crophopper's behavior to default! re set to change"
    hopper_redirect_fail: "you can only redirect to chests on your plot!!"
    no_permission: "&b&lAscendPvP &7> You do not have permission to use that command!"
    incorrect_usage: "&b&lAscendPvP &7> Incorrect usage! Try: &b/crophopper (player)"
    player_offline: "&b&lAscendPvP &7> That player is offline!"
    crophopper_success: "&b&lAscendPvP &7> Player successfully given a Crop Hopper!"
    crophopper_given: "&b&lAscendPvP &7> You have been given a Crop Hopper!"